# Generated by Django 4.2.30 on 2026-07-17 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('credits', models.PositiveIntegerField(verbose_name='Créditos que otorga')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio (USD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Disponible para la venta?')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Paquete de créditos',
                'verbose_name_plural': 'Paquetes de créditos',
                'db_table': 'billing_credit_pack',
                'ordering': ['display_order', 'price_usd'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('PAYPAL', 'PayPal'), ('PAYPHONE', 'PayPhone')], max_length=20)),
                ('provider_reference', models.CharField(db_index=True, help_text='orderId de PayPal o clientTransactionId de PayPhone', max_length=150)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credits', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.creditpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción de pago',
                'verbose_name_plural': 'Transacciones de pago',
                'db_table': 'billing_payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Saldo de créditos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billetera de créditos',
                'verbose_name_plural': 'Billeteras de créditos',
                'db_table': 'billing_credit_wallet',
            },
        ),
        migrations.CreateModel(
            name='CreditSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_spends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumo de créditos',
                'verbose_name_plural': 'Consumos de créditos',
                'db_table': 'billing_credit_spend',
                'ordering': ['-created_at'],
            },
        ),
    ]
