# Generated by Django 4.2.30 on 2026-07-17 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('ACCOUNT_VERIFICATION', 'Verificación de cuenta'), ('RESEND_VERIFICATION_CODE', 'Reenvío de código'), ('PASSWORD_RECOVERY', 'Recuperación de contraseña'), ('CUSTOM_NOTIFICATION', 'Notificación personalizada'), ('ATTACHMENT_NOTIFICATION', 'Notificación con adjunto')], max_length=40)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarea de correo',
                'verbose_name_plural': 'Cola de correos',
                'db_table': 'email_auth_email_task',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Control de la cola',
                'verbose_name_plural': 'Control de la cola',
                'db_table': 'email_auth_queue_control',
            },
        ),
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactiva (pendiente de verificación)'), ('ACTIVE', 'Activa')], default='INACTIVE', max_length=20, verbose_name='Estado de la cuenta')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='¿MFA activo?')),
                ('mfa_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('pending_mfa_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('recovery_token', models.CharField(blank=True, max_length=128, null=True)),
                ('recovery_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de seguridad',
                'verbose_name_plural': 'Perfiles de seguridad',
                'db_table': 'email_auth_security_profile',
            },
        ),
    ]
