# Generated by Django 4.2.30 on 2026-05-05 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=100, unique=True, verbose_name='ID del Número de Teléfono')),
                ('waba_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='WABA ID')),
                ('display_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número a mostrar')),
                ('business_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Negocio')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Token de Acceso')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor de API',
                'verbose_name_plural': 'Proveedores de API',
                'db_table': 'api_providers',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Campaña')),
                ('message_template', models.TextField(help_text='Usa {{variable}} para personalizar.', verbose_name='Plantilla del Mensaje')),
                ('media_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de Imagen/Adjunto')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('running', 'En Curso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Programada para')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='Número de WhatsApp')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Completo')),
                ('tags', models.CharField(blank=True, help_text='Para segmentar (ej: clientes, leads)', max_length=255, null=True, verbose_name='Etiquetas')),
                ('custom_data', models.JSONField(blank=True, help_text='Variables extra para plantillas', null=True, verbose_name='Datos Extra')),
                ('is_opted_out', models.BooleanField(default=False, verbose_name='¿No desea recibir mensajes?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Teléfono Destino/Origen')),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], max_length=15, verbose_name='Dirección')),
                ('message_type', models.CharField(default='text', max_length=50, verbose_name='Tipo de Mensaje')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado de Entrega')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Log de Error')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mass_sender.campaign', verbose_name='Campaña')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mass_sender.apiprovider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'messages',
            },
        ),
    ]
