# Generated by Django 4.2.30 on 2026-05-06 02:03

from django.db import migrations, models
import django.db.models.deletion
import mass_sender.models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='media_file',
            field=models.FileField(blank=True, help_text='Sube una imagen (JPG, PNG, WEBP) o video (MP4). Si subes archivo, tiene prioridad sobre la URL.', null=True, upload_to=mass_sender.models.campaign_media_upload_path, verbose_name='Subir Imagen o Video'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen/Adjunto (opcional)'),
        ),
        migrations.CreateModel(
            name='CampaignProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='Total de contactos')),
                ('sent', models.IntegerField(default=0, verbose_name='Enviados')),
                ('failed', models.IntegerField(default=0, verbose_name='Fallidos')),
                ('is_running', models.BooleanField(default=False, verbose_name='¿En ejecución?')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Último error')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='mass_sender.campaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Progreso de Campaña',
                'verbose_name_plural': 'Progreso de Campañas',
                'db_table': 'campaign_progress',
            },
        ),
    ]
