# Generated by Django 4.2.30 on 2026-08-04 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _asignar_dueno_a_campanas_existentes(apps, schema_editor):
    """
    Backfill: antes de este cambio, Campaign no tenía dueño y cualquier
    usuario autenticado podía ver el archivo de cualquier campaña (IDOR
    detectado en la matriz de seguridad de benchmark/seguridad_tokens.py).

    Las campañas creadas antes de esta migración se asignan, en este
    orden de preferencia:
      1. Al usuario cuyo username o email coincide con
         MASSSEND_OWNER_BACKFILL (variable de entorno opcional, útil si
         hay varias cuentas y quieres elegir explícitamente cuál).
      2. Si no está definida esa variable, al primer superusuario cuyo
         username o email NO sea el genérico "admin" (evita adjudicar
         las campañas reales al usuario admin de build automático).
      3. Como último recurso, al primer superusuario que exista.
    Las campañas nuevas ya se crean con owner=user desde la vista
    api_campanas_list, así que este backfill solo corre una vez.
    """
    import os

    Campaign = apps.get_model('mass_sender', 'Campaign')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    objetivo = os.environ.get('MASSSEND_OWNER_BACKFILL', '').strip()
    dueno = None
    if objetivo:
        dueno = User.objects.filter(username=objetivo).first() or User.objects.filter(email=objetivo).first()
    if dueno is None:
        dueno = User.objects.filter(is_superuser=True).exclude(username='admin').order_by('id').first()
    if dueno is None:
        dueno = User.objects.filter(is_superuser=True).order_by('id').first()

    if dueno is not None:
        Campaign.objects.filter(owner__isnull=True).update(owner=dueno)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mass_sender', '0004_campaign_target_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Usuario propietario de la campaña. Requerido para aislar el acceso entre cuentas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Dueño'),
        ),
        migrations.RunPython(_asignar_dueno_a_campanas_existentes, migrations.RunPython.noop),
    ]
